### PR TITLE
Choropleth maps of sum of PM2.5 by county for each of the 4 years of dat...

### PR DESCRIPTION
**Pull request by BillSeliger**
...a given in the Exploratory Data Analysis Project 2.

### CODE REVIEW

**Comment by seankross** [comment]
Hi @BillSeliger, 
This is cool! Do you think you could host this somewhere on your GitHub, and then just add a link to the EDA page?

**Comment by BillSeliger** [comment]
@seankross - Thanks, I am enjoying leaning about the mapping capabilities of R (and I'm loving the JHU Data Science specialization!)  Do I just create a .md file with a short explanation and link to my Github repo with this and then submit a pull request with that .md file?  I'm still new to Github and learning my way.

Thanks!

**Comment by seankross** [comment]
Hi @BillSeliger,
If I were you I would:
- Add these materials to some GitHub repository of your own.
- Modify `eda.md` so that it links to your GitHub repository.

Let me know if you have any other questions.

**Comment by BillSeliger** [comment]
I think I have it correct this time - I created Emissions_Choropleth_Maps.md with just a link to the full markdown file in my own repository.  Thanks for your help with this!

**Comment by seankross** [comment]
No problem @BillSeliger, always happy to help!

**Pull request merged**
