### PR TITLE
metricsgraphic tutorial

### PR DESCRIPTION
**Pull request by DocOfi**
@seankross  added a new presentation and hope you don't mind if i added my names as a community contributor
@rdpeng created a presentation based on your presentation in EDA course

### CODE REVIEW

**Comment by seankross** [comment]
@DocOfi Did you mean to close this or do you want it to be merged?

**Comment by DocOfi** [comment]
@seankross I meant it to be merged. Sorry, i didn't know what clicking on the close button did :-P

**Comment by seankross** [comment]
Thank you!

**Comment by DocOfi** [comment]
Thanks again.  Sorry for the mix-up.

**Pull request merged**
