### PR TITLE
Update curated.md

### PR DESCRIPTION
**Pull request by Aratinga**
Temporary location for a file referenced in Toolbox. Ron Meir has given permission.

### CODE REVIEW

**Comment by seankross** [comment]
Thank you!

**Comment by Aratinga** [comment]
Sorry, I think I screwed it up. The link isn't a link. Can you fix it or do
I have to try again? I tried to follow the style in the other lines.


   -

   "No trees were killed and no animals were harmed in the creation of this
   message. However, many electrons were terribly inconvenienced."

**Comment by seankross** [comment]
I should have caught that. I'll fix it now.

**Comment by Aratinga** [comment]
Thanks!


   -

   "No trees were killed and no animals were harmed in the creation of this
   message. However, many electrons were terribly inconvenienced."

**Comment by Aratinga** [comment]
I now have an interesting problem. I was "hosting" this file because the
link (from Machine Learning intro, slide 5) was broken. Either Professor
Leek fixed it, or the author replaced it on the Technion site.

I think it is a useful item, but it should be under Machine Learning, and
here is the URL, which now works:
http://webee.technion.ac.il/people/rmeir/BoostingTutorial.pdf

Do you suggest I submit another update to our Curated site? Or can you fix
it?


   -

   "No trees were killed and no animals were harmed in the creation of this
   message. However, many electrons were terribly inconvenienced."

**Comment by seankross** [comment]
I'll do whatever you wish, but I think it's valuable to have it hosted on GitHub in case that link stops working.

**Comment by Aratinga** [comment]
I think you are right. It is a 2002 lecture so not likely to have updates.

By the way, our colleagues have quite a collection of interesting helpful
things to link to. Should I consider adding them to this page, now that I
sort of know how? (And what exactly did I screw up when I added that line?)


   -

   "No trees were killed and no animals were harmed in the creation of this
   message. However, many electrons were terribly inconvenienced."

**Comment by seankross** [comment]
Your additions would be great! Last time you mistakenly put a space between the bracket and the parenthesis:

This code: `[Example](www.example.com)`
Produces this: [Example](www.example.com)

While this code (notice the space): `[Example] (www.example.com)`
Produces this: \[Example] (www.example.com)

This website is written in a markup language called markdown. You can find GitHub's markdown guide here: https://guides.github.com/features/mastering-markdown/

**Comment by Aratinga** [comment]
Ugh! A space! Yes, markdown is just another damn language with finicky
syntax...


   -

   "No trees were killed and no animals were harmed in the creation of this
   message. However, many electrons were terribly inconvenienced."

**Comment by Aratinga** [comment]
I just put a lot of links in, before the R class hits the fan.

Sandy


   -

   "No trees were killed and no animals were harmed in the creation of this
   message. However, many electrons were terribly inconvenienced."

**Pull request merged**
