### PR TITLE
Add articles to R Programming page

### PR DESCRIPTION
**Pull request by lgreski**

### CODE REVIEW

**Comment by seankross** [comment]
@lgreski I don't believe there is a capstone page.

**Comment by lgreski** [comment]
Capstone page will be in my next merge.

**Comment by seankross** [comment]
Would you mind taking the link out until the link is live? (Or I can just wait until you add the commit.)

**Comment by lgreski** [comment]
I will add the other commit this evening US hours.

Len

----------------------------------------
Len Greski
Voice: 847-404-3079
Pardon the brevity, sent from mobile device

**Comment by lgreski** [comment]
Added the capstone.md page.

**Comment by seankross** [comment]
@lgreski Is this ready to merge?

**Comment by lgreski** [comment]
Yes, it has been ready to merge since Tuesday when I committed capstone.md.

 

Regards,

 

Len

**Comment by seankross** [comment]
Awesome, thanks Len!

**Comment by lgreski** [comment]
You're welcome. I apologize about the initial issue. I didn't realize that once I'd submitted a pull request, that subsequent commits to my version of the repository are automatically included in the pull. I thought I had submitted a complete package and was waiting for it to be completed before submitting the updated index and capstone pages. I"m usually pretty conscientious about making my pull requests complete units of work.

**Comment by lgreski** [comment]
@seankross looks good, Capstone page is available from the home page, correctly brings up capstone.md, and all links on capstone.md bring up the correct pages.

**Comment by seankross** [comment]
Don't worry about it! One suggestion: you could create a separate branch for each "unit of work" and then initiate the PR from that branch. That way your commits to other branches wouldn't show up.

**Comment by lgreski** [comment]
That's a good point. Usually when I contribute content to the DSS repository the units of work are smaller, so no need for a separate branch.

**Comment by lgreski** [comment]
That's a good point. Usually when I contribute content to the DSS repository the units of work are smaller, so no need for a separate branch.

**Pull request merged**
